server:
  port: 80

spring:
  zipkin:
    enabled: true
    base-url: http://10.84.0.19:9411
    service:
      name: api-gateway-application
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
          allowedOrigins: "*"
          allowedHeaders: "*"
          allowedMethods:
          - GET
          - POST
      routes:
        - id: auth-service
          uri: http://10.88.10.211:9090
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallback/auth
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/product/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: product
                fallbackUri: forward:/fallback/product
        - id: sales-service
          uri: http://localhost:9092
          predicates:
            - Path=/sales/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: sales
                fallbackUri: forward:/fallback/sales
        - id: user-service
          uri: http://10.88.5.139:9093
          predicates:
            - Path=/user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallback/user
      default-filters:
        #       http://localhost/auth/findbyid/1
        #       (?<segment>.*) -> auth/findbyid/1
        #       /$\{segment} -> http://localhost:9090/auth/findbyid/1
        - RewritePath= /(?<segment>.*), /$\{segment}
