server:
  port: 80

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
      default-filters:
#       http://localhost/auth/findbyid/1
#       (?<segment>.*) -> auth/findbyid/1
#       /$\{segment} -> http://localhost:9090/auth/findbyid/1
        - RewritePath= /(?<segment>.*), /$\{segment}