server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-micro-service-application
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1316
    url: jdbc:postgresql://localhost:5432/AuthDB
  jpa:
    hibernate:
      ddl-auto: update
# Key/Value kullanımında : dan sonra mutlaka boşluk bırakın
# key: deger

#   ÖNEMLİ
# Şifre gibi başkalarının görmesini istemediğimiz bilgilerin yml dosyasında
# dahi tutulması çok sakıncalıdır. Bu nedenle bu bilgilerin gizlenmesi gereklidir.
# Bu işlemi yapabilmek için EnvironmentVariable- Sistem Ortam Değişkenleri
# kullanmak gereklidir.
authservice:
  bunu-ben-yazdim:
    secret-key: ${JAVA_SECRETKEY}
    issuer: ${JAVA6_ISSUER}
