server:
  port: 9100

spring:
  zipkin:
    service:
      name: elastic-service
    base-url: http://localhost:9411
    enabled: true
  elasticsearch:
    uris: http://localhost:9200

authservice:
  bunu-ben-yazdim:
    secret-key: ${JAVA_SECRETKEY}
    issuer: ${JAVA6_ISSUER}